---
title: "TD3"
format: html
editor: visual
---
```{r}
df_velo<- read.csv("244400404_comptages-velo-nantes-metropole.csv", sep=";", stringsAsFactors = FALSE)
str(df_velo)
```

question 1
```{r}
df_b_788 <- df_velo[df_velo$NumĂ©ro.de.boucle == 745, ] 
df_b_805 <- df_velo[df_velo$NumĂ©ro.de.boucle == 987, ]

# df jours
df_d_0105 <- df_velo[df_velo$Jour == "2025-02-01", ]
df_d_1506 <- df_velo[df_velo$Jour == "2025-08-15", ]
```

question 2
```{r}
filtre_anomalie <- function(df) {
  df_filtre <- df[!(df$anomalie %in% c("Forte", "Faible")), ]
  return(df_filtre)
}

filtre_anomalie(df_b_788)
filtre_anomalie(df_b_805)
filtre_anomalie(df_d_0105)
filtre_anomalie(df_d_1506)
```

question 3
```{r}
compter_nombre_trajets <- function(df){
  sum(df$Total, na.rm = TRUE)
}

compter_nombre_trajets(df_b_788)
compter_nombre_trajets(df_b_805)
compter_nombre_trajets(df_d_0105)
compter_nombre_trajets(df_d_1506)
```
question 4
```{r}
nombre_boucles <- function(df){
  length(unique(df$NumĂ©ro.de.boucle))
}
nombre_boucles(df_velo)
nombre_boucles(df_b_788)
nombre_boucles(df_b_805)
nombre_boucles(df_d_0105)
nombre_boucles(df_d_1506)
```


